### ISSUE TITLE
Enumerable#all? in rubyVM.evalAsync causes SystemStackError

### ISSUE THREAD

**Issue by shugo** [ruby/ruby.wasm#133]
It seems that Enumerable#all? in rubyVM.evalAsync causes SystemStackError:

```
<html>
  <script src="https://cdn.jsdelivr.net/npm/ruby-head-wasm-wasi@0.5.0/dist/browser.script.iife.js"></script>

  <button id="start">Start</button>

  <script type="text/javascript">
    async function start() {
      await window.rubyVM.evalAsync("p (0..3).all? { |i| i.even? }")
    }
    var startButton = document.getElementById("start")
    startButton.addEventListener("click", () => {
      start()
    }, false)
  </script>
</html>
```

```
browser.script.iife.js:1505 Uncaught (in promise) Error: SystemStackError: stack level too deep
    at checkStatusTag (browser.script.iife.js:1505:21)
    at browser.script.iife.js:1535:11
    at wrapRbOperation (browser.script.iife.js:1512:18)
    at callRbMethod (browser.script.iife.js:1533:14)
    at RbValue.call (browser.script.iife.js:1390:30)
    at browser.script.iife.js:1293:18
    at new Promise (<anonymous>)
    at RubyVM.evalAsync (browser.script.iife.js:1292:18)
    at start (test.html:8:27)
    at HTMLButtonElement.<anonymous> (test.html:12:7)
checkStatusTag @ browser.script.iife.js:1505
（匿名） @ browser.script.iife.js:1535
wrapRbOperation @ browser.script.iife.js:1512
callRbMethod @ browser.script.iife.js:1533
call @ browser.script.iife.js:1390
（匿名） @ browser.script.iife.js:1293
evalAsync @ browser.script.iife.js:1292
start @ test.html:8
（匿名） @ test.html:12
await in （匿名）（非同期）
（匿名） @ test.html:12
```

Enumerable#all? in rubyVM.eval works fine.

**Comment by kateinoigakukun** [comment]
`evalAsync` internally uses Fiber, and its stack size 256kb is smaller than main stack (16mb). You can extend the stack size by environment variable like this
https://github.com/kateinoigakukun/irb.wasm/blob/1d6696ea1c6fa5206b7e6a0eab3468c409545c8c/src/irb-worker.ts#L99

But I know its not ideal solution, so I'll try to reduce stack consumptions in vm_eval.

**Comment by kateinoigakukun** [comment]
I improved stack usage in https://github.com/ruby/ruby.wasm/pull/214, and the `Enumerable#all?` code itself now works. We still have some optimization space around setjmp buffer, but I'll have another look if the problem will be revealed again.

**Comment by shugo** [comment]
@kateinoigakukun Thank you!
