### ISSUE TITLE
Recent wasi-sdk broke CRuby build

### ISSUE THREAD

**Issue by ongaeshi** [ruby/ruby.wasm#187]
I am trying building CRuby from source but I get errors around openssl. 

windows11 WSL

```
$ uname -a
Linux LAPTOP-70JOP1HD 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

# log

```
$ rake build:3_2-wasm32-unknown-wasi-full-js
make: Nothing to be done for 'rbconfig.rb'.
creating Makefile
make: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/js'
make: 'js.a' is up to date.
make: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/js'
creating Makefile
make: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/witapi'
make: 'witapi.a' is up to date.
make: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/witapi'
rm -rf .bundle/gems/debug-1.7.1/
rm -rf .bundle/gems/rbs-2.8.2/
        BASERUBY = /home/ongaeshi/WslCode/ruby.wasm/build/x86_64-pc-linux/baseruby-3_2/opt/bin/ruby --disable=gems
        CC = /home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/tool/wasm-clangw /home/ongaeshi/wasi-sdk-19.0/bin/clang
        LD = /home/ongaeshi/wasi-sdk-19.0/bin/clang
        LDSHARED = /home/ongaeshi/wasi-sdk-19.0/bin/clang
        CFLAGS = -fdeclspec -O3 -fno-fast-math -g0 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wundef   -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_GETPID -D_WASI_EMULATED_PROCESS_CLOCKS 
        XCFLAGS = -DWASM_SETJMP_STACK_BUFFER_SIZE=24576 -DWASM_FIBER_STACK_BUFFER_SIZE=24576 -DWASM_SCAN_STACK_BUFFER_SIZE=24576 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -I. -I.ext/include/wasm32-wasi -I/home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/include -I/home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2 -I/home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/enc/unicode/15.0.0 
        CPPFLAGS = -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_GETPID -D_WASI_EMULATED_PROCESS_CLOCKS   
        DLDFLAGS = -Xlinker -zstack-size=16777216 /home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/wasi-vfs-0.1.1/libwasi_vfs.a @/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/js/link.filelist @/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/witapi/link.filelist /home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js-ext/extinit.o  
        SOLIBS =  -lcrypt -lm -lwasi-emulated-mman -lwasi-emulated-signal -lwasi-emulated-getpid -lwasi-emulated-process-clocks 
        LANG = C.UTF-8
        LC_ALL = 
        LC_CTYPE = 
        MFLAGS = 
        RUSTC = rustc
        YJIT_RUSTC_ARGS = --crate-name=yjit --crate-type=staticlib --edition=2021 -g -C opt-level=3 -C overflow-checks=on '--out-dir=/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/yjit/target/release/' /home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/yjit/src/lib.rs
clang version 15.0.7
Target: wasm32-unknown-wasi
Thread model: posix
InstalledDir: /home/ongaeshi/wasi-sdk-19.0/bin
generating enc.mk
making srcs under enc
make[1]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js'
make[1]: Nothing to be done for 'srcs'.
make[1]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js'
generating transdb.h
transdb.h updated
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk unchanged
make[1]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/bigdecimal'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/bigdecimal'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/coverage'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/coverage'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/date'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/date'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/digest'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/digest'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/digest/sha2'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/digest/sha2'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/json'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/json'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/monitor'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/monitor'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/nkf'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/nkf'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/objspace'
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/objspace'
make[2]: Entering directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/openssl'
compiling /home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/ext/openssl/ossl_x509store.c
/home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/ext/openssl/ossl_x509store.c:190:5: error: incomplete definition of type 'struct x509_store_st'
    X509_STORE_set_ex_data(store, store_ex_verify_cb_idx, (void *)cb);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ongaeshi/WslCode/ruby.wasm/build/checkouts/3_2/ext/openssl/openssl_missing.h:31:25: note: expanded from macro 'X509_STORE_set_ex_data'
        CRYPTO_set_ex_data(&(x)->ex_data, (idx), (data))
                            ~~~^
/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/openssl-3.0.5/opt/usr/local/include/openssl/types.h:164:16: note: forward declaration of 'struct x509_store_st'
typedef struct x509_store_st X509_STORE;
               ^
1 error generated.
make[2]: *** [Makefile:327: ossl_x509store.o] Error 1
make[2]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/ext/openssl'
make[1]: *** [exts.mk:207: ext/openssl/static] Error 2
make[1]: Leaving directory '/home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js'
make: *** [uncommon.mk:331: build-ext] Error 2
rake aborted!
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /home/ongaeshi/WslCode/ruby.wasm/build/wasm32-unknown-wasi/3_2-wasm32-unknown-wasi-full-js/install
/home/ongaeshi/WslCode/ruby.wasm/lib/ruby_wasm/build_system/product/crossruby.rb:157:in `build'
/home/ongaeshi/WslCode/ruby.wasm/lib/ruby_wasm/rake_task.rb:77:in `block in initialize'
Tasks: TOP => build:3_2-wasm32-unknown-wasi-full-js
(See full trace by running task with --trace)
```

**Comment by kateinoigakukun** [comment]
Hmm, could you try again after `rake clean`?
