### ISSUE TITLE
Using Node.js 20, rake npm:ruby-head-wasm-wasi:check does not work

### ISSUE THREAD

**Issue by ledsun** [ruby/ruby.wasm#314]
## What happened.

I installed Node.js 20.8.0 and ran `rake npm:ruby-head-wasm-wasi:check` and got the following error:

```
►rake npm:ruby-head-wasm-wasi:check
npm test

> ruby-head-wasm-wasi@2.2.0 test
> RUBY_NPM_PACKAGE_ROOT=../ruby-head-wasm-wasi npm -C ../ruby-wasm-wasi run test:run


> @ruby/wasm-wasi@2.2.0 test:run
> npm run test:unit && npm run test:jest && npm run test:e2e


> @ruby/wasm-wasi@2.2.0 test:unit
> ./tools/run-test-unit.mjs

(node:66391) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.version" property must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at new WASI (node:wasi:51:5)
    at instantiateNodeWasi (file:///home/ledsun/ruby.wasm/packages/npm-packages/ruby-wasm-wasi/tools/run-test-unit.mjs:30:16)
    at async test (file:///home/ledsun/ruby.wasm/packages/npm-packages/ruby-wasm-wasi/tools/run-test-unit.mjs:128:24)
    at async main (file:///home/ledsun/ruby.wasm/packages/npm-packages/ruby-wasm-wasi/tools/run-test-unit.mjs:162:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.8.0
npm ERR! Lifecycle script `test:unit` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @ruby/wasm-wasi@2.2.0
npm ERR!   at location: /home/ledsun/ruby.wasm/packages/npm-packages/ruby-wasm-wasi
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: ruby-head-wasm-wasi@2.2.0
npm ERR!   at location: /home/ledsun/ruby.wasm/packages/npm-packages/ruby-head-wasm-wasi
rake aborted!
Command failed with status (1): [npm test]
/home/ledsun/ruby.wasm/tasks/packaging.rake:21:in `block (4 levels) in <top (required)>'
Tasks: TOP => npm:ruby-head-wasm-wasi:check
(See full trace by running task with --trace)
```

It worked fine using Node.js 18.8.2.

## What I tried

Added `version` property to the argument of the WASI constructor.

https://github.com/ruby/ruby.wasm/blob/5a28621732af565f888648da5bdd1f3fc6fd398e/packages/npm-packages/ruby-wasm-wasi/tools/run-test-unit.mjs#L30-L39

I have tried both `unstable` and `preview1` according to https://nodejs.org/docs/latest-v20.x/api/wasi.html.
The test ended with a `Segmentation fault`.

```
ledsun@MSI:~/ruby.wasm►rake npm:ruby-head-wasm-wasi:check
npm test

> ruby-head-wasm-wasi@2.2.0 test
> RUBY_NPM_PACKAGE_ROOT=../ruby-head-wasm-wasi npm -C ../ruby-wasm-wasi run test:run


> @ruby/wasm-wasi@2.2.0 test:run
> npm run test:unit && npm run test:jest && npm run test:e2e


> @ruby/wasm-wasi@2.2.0 test:unit
> ./tools/run-test-unit.mjs

(node:68755) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Ignoring debug-1.8.0 because its extensions are not built. Try: gem pristine debug --version 1.8.0
Ignoring racc-1.7.3 because its extensions are not built. Try: gem pristine racc --version 1.7.3
Ignoring rbs-3.3.2 because its extensions are not built. Try: gem pristine rbs --version 3.3.2
Loaded suite /__root__/test/test_unit
Started
Segmentation fault
npm ERR! Lifecycle script `test:unit` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @ruby/wasm-wasi@2.2.0
npm ERR!   at location: /home/ledsun/ruby.wasm/packages/npm-packages/ruby-wasm-wasi
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: ruby-head-wasm-wasi@2.2.0
npm ERR!   at location: /home/ledsun/ruby.wasm/packages/npm-packages/ruby-head-wasm-wasi
rake aborted!
Command failed with status (1): [npm test]
/home/ledsun/ruby.wasm/tasks/packaging.rake:21:in `block (4 levels) in <top (required)>'
Tasks: TOP => npm:ruby-head-wasm-wasi:check
(See full trace by running task with --trace)
```

**Comment by terrablue** [comment]
I can confirm this doesn't work with Node.js 21 either. By the way, the fix to https://github.com/ruby/ruby.wasm/blob/main/packages/npm-packages/ruby-wasm-wasi/tools/run-test-unit.mjs#L30 (adding `{ version: "preview1" }`) can be done independently of that. Should I send a PR?

**Comment by kateinoigakukun** [comment]
@terrablue Yes, that would be helpful :)

**Comment by terrablue** [comment]
@kateinoigakukun is it possible to run at least *part* of the tests or isolate this problem down to a particular test? I would like to start contributing, but it's hard to know if I'm introducing regressions otherwise.

**Comment by kateinoigakukun** [comment]
I think the easiest way at this time is just using Node.js older than 19

**Comment by ralyodio** [comment]
we are using node 20 LTS in production.

**Comment by kateinoigakukun** [comment]
I suspect https://github.com/nodejs/node/pull/43697/ includes something wrong
